- id: 1
  key: renminbi
  code: cny
  symbol: "¥"
  coin: false
  precision: 2
  assets:
    accounts:
      -
        bank: 'Bank of China'
        address: '6225 0885 6022 3501'
        password: '111111'
        tel: '95555'
- id: 2
  key: satoshi
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 100
  rpc: http://hitback:5dfa6363287b606b7b863e0fe994234c@127.0.0.1:18332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: mh5KPKSdWATnHXCcsPFaxWW1ooFz57QvXN

